import os
from crewai import Agent, Task, Crew, Process
from langchain_community.llms import Ollama

# used for Ollama and a local model
ollama_openhermes = Ollama(model="openhermes")

# either use api key for gpt, or just some string for local
os.environ["OPENAI_API_KEY"] = "sk-1111"


# # Create a Researcher agent
# researcher = Agent(
#     role='Researcher',
#     goal='Develop comprehensive ideas to teach a beginner about a specified topic',
#     backstory='With deep expertise in the subject, your mission is to break down complex concepts and create insightful explanations for beginners.',
#     verbose=True,
#     llm=ollama_openhermes
# )

# # Create a Writer agent
# writer = Agent(
#     role='Writer',
#     goal='Compose a clear and engaging piece of text to explain the chosen topic',
#     verbose=True,
#     backstory='As a skilled communicator, your task is to transform the research ideas provided by the Researcher into an informative and accessible text.',
#     llm=ollama_openhermes
# )

# # Create an Examiner agent
# examiner = Agent(
#     role='Examiner',
#     goal='Craft 2-3 test questions and provide correct answers to evaluate comprehension of the created text',
#     verbose=True,
#     backstory='With an expertise in assessment, your role is to create thought-provoking questions to gauge the understanding of learners based on the written text.',
#     llm=ollama_openhermes
# )

# # Task for the Researcher
# research_task = Task(
#     description='Develop comprehensive ideas to teach a beginner about the specified topic',
#     agent=researcher
# )

# # Task for the Writer
# write_task = Task(
#     description='Compose a clear and engaging piece of text to explain the chosen topic using research ideas',
#     agent=writer
# )

# # Task for the Examiner
# exam_task = Task(
#     description='Craft 2-3 test questions and provide correct answers to evaluate comprehension of the created text',
#     agent=examiner
# )

# # Instantiate your crew with a sequential process
# educational_crew = Crew(
#     agents=[researcher, writer, examiner],
#     tasks=[research_task, write_task, exam_task],
#     process=Process.sequential,
#     llm=ollama_openhermes
# )

# # Get your crew to work!
# result = educational_crew.kickoff()

# print("######################")
# print(result)
class InteractiveAgent(Agent):
    def interact(self, prompt):
        # Allow the agent to interact with the user or external inputs
        return self.llm.complete(prompt)

# Create a Researcher agent
researcher = InteractiveAgent(
    role='Researcher',
    goal='Generate innovative ideas for teaching someone new to backend engineering',
    backstory='An imaginative expert in the field, you thrive on creativity and innovation, aiming to redefine how complex topics are introduced to beginners.',
    verbose=True,
    llm=ollama_openhermes
)

# Create a Writer agent
writer = InteractiveAgent(
    role='Writer',
    goal='Craft a dynamic and immersive piece of text to explain the chosen topic',
    verbose=True,
    backstory='A storyteller at heart, your task is to transform the innovative ideas generated by the Researcher into a captivating narrative that engages and educates.',
    llm=ollama_openhermes
)

# Create an Examiner agent
examiner = InteractiveAgent(
    role='Examiner',
    goal='Generate dynamic and adaptive test questions with varying difficulty levels',
    verbose=True,
    backstory='With a focus on personalized assessment, your role is to create dynamic test questions that adapt to the learner’s progress, ensuring a tailored and effective evaluation.',
    llm=ollama_openhermes
)

# Task for the Researcher
research_task = Task(
    description='Generate innovative ideas for teaching someone new to backend engineering',
    agent=researcher
)

# Task for the Writer
write_task = Task(
    description='Craft a dynamic and immersive piece of text to explain the chosen topic using innovative ideas',
    agent=writer
)

# Task for the Examiner
exam_task = Task(
    description='Generate dynamic and adaptive test questions with varying difficulty levels',
    agent=examiner
)

# Instantiate the crew with a sequential process
innovative_educational_crew = Crew(
    agents=[researcher, writer, examiner],
    tasks=[research_task, write_task, exam_task],
    process=Process.sequential,
    llm=ollama_openhermes
)

# Get the crew to work!
result = innovative_educational_crew.kickoff()

print("######################")
print(result)